embroidery_website/embroidery_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^runbun/', include('runbun.urls')),
    url(r'^admin/', admin.site.urls),
]

embroidery_website/runbun/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

app_name = 'runbun'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^reviews/$', views.reviews, name='reviews'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', views.about, name='about'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^cart/$', views.cart, name='cart'),
]

embroidery_website/runbun/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

embroidery_website/runbun/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


def index(request):
    context = {}

    return render(request, 'runbun/index.html', context)


def gallery(request):
    context = {}

    return render(request, 'runbun/gallery.html', context)


def reviews(request):
    context = {}

    return render(request, 'runbun/reviews.html', context)


def contact(request):
    context = {}

    return render(request, 'runbun/contact.html', context)


def about(request):
    context = {}

    return render(request, 'runbun/about.html', context)


def signin(request):
    context = {}

    return render(request, 'runbun/signin.html', context)



def cart(request):
    context = {}

    return render(request, 'runbun/cart.html', context)

embroidery_website/runbun/templates/runbun/about.html
<!DOCTYPE html>

<html>
<head>
    {% load static %}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'runbun/css/style.css' %}">

    <title>runBun</title>
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="{% url 'runbun:index' %}">
          <img src="{% static 'runbun/img/runBun_logo.gif' %}" alt="Home" id="runbun-logo">run<strong>Bun</strong>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-left text-center">
          <li><a href="#shirts" class="nav-link current">Shirts</a></li>
          <li><a href="#jackets" class="nav-link">Jackets</a></li>
          <li><a href="#hats" class="nav-link">Hats</a></li>
          <li><a href="#backpacks" class="nav-link">Backpacks</a></li>
          <li><a href="#custom-items" class="nav-link">Custom Items</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right text-center">
          <li><a href="#contact-us" class="nav-link">Contact Us</a></li>
          <li><a href="{% url 'runbun:about' %}" class="nav-link">About Us</a></li>
          <li><a href="{% url 'runbun:signin' %}" class="nav-link signin" id="signin-btn"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Sign In</a></li>
          <li>
            <a href="{% url 'runbun:cart' %}" class="nav-link shopping-cart" id="shopping-cart-btn">
              <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
              <span class="badge badge-info">4</span>
            </a>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


    <div class="container">
      <div class="jumbotron">
        <h1>This is About</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
      </div>
	</div> <!--container-->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="{% static 'runbun/js/main.js' %}"></script>

</body>
</html>

embroidery_website/runbun/templates/runbun/cart.html
<!DOCTYPE html>

<html>
<head>
    {% load static %}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'runbun/css/style.css' %}">

    <title>runBun</title>
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="{% url 'runbun:index' %}">
          <img src="{% static 'runbun/img/runBun_logo.gif' %}" alt="Home" id="runbun-logo">run<strong>Bun</strong>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-left text-center">
          <li><a href="#shirts" class="nav-link current">Shirts</a></li>
          <li><a href="#jackets" class="nav-link">Jackets</a></li>
          <li><a href="#hats" class="nav-link">Hats</a></li>
          <li><a href="#backpacks" class="nav-link">Backpacks</a></li>
          <li><a href="#custom-items" class="nav-link">Custom Items</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right text-center">
          <li><a href="#contact-us" class="nav-link">Contact Us</a></li>
          <li><a href="{% url 'runbun:about' %}" class="nav-link">About Us</a></li>
          <li><a href="{% url 'runbun:signin' %}" class="nav-link signin" id="signin-btn"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Sign In</a></li>
          <li>
            <a href="{% url 'runbun:cart' %}" class="nav-link shopping-cart" id="shopping-cart-btn">
              <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
              <span class="badge badge-info">4</span>
            </a>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


    <div class="container">
      <div class="jumbotron">
        <h1>This is the Cart</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
      </div>
	</div> <!--container-->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="{% static 'runbun/js/main.js' %}"></script>

</body>
</html>

embroidery_website/runbun/templates/runbun/contact.html
<!DOCTYPE html>

<html>
<head>
    {% load static %}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'runbun/css/style.css' %}">

    <title>runBun</title>
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
       <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="{% url 'runbun:index' %}">
			<img src="{% static 'runbun/img/runBun_logo.gif' %}" alt="Home" id="runbun-logo">
			run<strong>Bun</strong>
		   </a>
         </div>

         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

           <ul class="nav navbar-nav navbar-right text-center">
             <li><a href="{% url 'runbun:index' %}" class="nav-link">Home</a></li>
             <li><a href="{% url 'runbun:gallery' %}" class="nav-link">Gallery</a></li>
             <li><a href="{% url 'runbun:reviews' %}" class="nav-link">Reviews</a></li>
             <li><a href="{% url 'runbun:contact' %}" class="nav-link current">Contact Us</a></li>
             <li><a href="{% url 'runbun:about' %}" class="nav-link">About Us</a></li>
             <li><a href="{% url 'runbun:signin' %}" class="nav-link signin" id="signin-btn">Sign In</a></li>
             <li><a href="{% url 'runbun:cart' %}" class="nav-link shopping-cart" id="shopping-cart-btn"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a></li>
           </ul>


         </div><!-- /.navbar-collapse -->
       </div><!-- /.container-fluid -->
    </nav>


    <div class="container">
      <div class="jumbotron">
        <h1>This is Contact</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
      </div>
	</div> <!--container-->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="{% static 'runbun/js/main.js' %}"></script>

</body>
</html>

embroidery_website/runbun/templates/runbun/gallery.html
<!DOCTYPE html>

<html>
<head>
    {% load static %}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'runbun/css/style.css' %}">

    <title>runBun</title>
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
       <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="{% url 'runbun:index' %}">
			<img src="{% static 'runbun/img/runBun_logo.gif' %}" alt="Home" id="runbun-logo">
			run<strong>Bun</strong>
		   </a>
         </div>

         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

           <ul class="nav navbar-nav navbar-right text-center">
             <li><a href="{% url 'runbun:index' %}" class="nav-link">Home</a></li>
             <li><a href="{% url 'runbun:gallery' %}" class="nav-link current">Gallery</a></li>
             <li><a href="{% url 'runbun:reviews' %}" class="nav-link">Reviews</a></li>
             <li><a href="{% url 'runbun:contact' %}" class="nav-link">Contact Us</a></li>
             <li><a href="{% url 'runbun:about' %}" class="nav-link">About Us</a></li>
             <li><a href="{% url 'runbun:signin' %}" class="nav-link signin" id="signin-btn">Sign In</a></li>
             <li><a href="{% url 'runbun:cart' %}" class="nav-link shopping-cart" id="shopping-cart-btn"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a></li>
           </ul>


         </div><!-- /.navbar-collapse -->
       </div><!-- /.container-fluid -->
    </nav>


    <div class="container">
      <div class="jumbotron">
        <h1>This is the Gallery</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
      </div>
	</div> <!--container-->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="{% static 'runbun/js/main.js' %}"></script>

</body>
</html>

embroidery_website/runbun/templates/runbun/index.html
<!DOCTYPE html>

<html>
<head>
    {% load static %}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'runbun/css/style.css' %}">

    <title>runBun</title>
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="{% url 'runbun:index' %}">
          <img src="{% static 'runbun/img/runBun_logo.gif' %}" alt="Home" id="runbun-logo">run<strong>Bun</strong>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-left text-center">
          <li><a href="#shirts" class="nav-link current">Shirts</a></li>
          <li><a href="#jackets" class="nav-link">Jackets</a></li>
          <li><a href="#hats" class="nav-link">Hats</a></li>
          <li><a href="#backpacks" class="nav-link">Backpacks</a></li>
          <li><a href="#custom-items" class="nav-link">Custom Items</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right text-center">
          <li><a href="#contact-us" class="nav-link">Contact Us</a></li>
          <li><a href="{% url 'runbun:about' %}" class="nav-link">About Us</a></li>
          <li><a href="{% url 'runbun:signin' %}" class="nav-link signin" id="signin-btn"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Sign In</a></li>
          <li>
            <a href="{% url 'runbun:cart' %}" class="nav-link shopping-cart" id="shopping-cart-btn">
              <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
              <span class="badge badge-info">4</span>
            </a>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<!--
    <div class="container">
      <div class="jumbotron">
        <h1>This is Home</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
      </div>
    </div> -->

    <!--
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>


      <div class="carousel-inner">
        <div class="item active">
          <img src="https://www.projects-software.com/wp-content/uploads/2014/10/hdr-projects-3-standard_slider_2.jpg" alt="Los Angeles">
        </div>

        <div class="item">
          <img src="https://www.projects-software.com/wp-content/uploads/2014/10/hdr-projects-3-standard_slider_2.jpg" alt="Chicago">
        </div>

        <div class="item">
          <img src="https://www.projects-software.com/wp-content/uploads/2014/10/hdr-projects-3-standard_slider_2.jpg" alt="New York">
        </div>
      </div>


      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>-->

  <a id="back-to-top-btn"><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></a>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="{% static 'runbun/js/main.js' %}"></script>

</body>
</html>

embroidery_website/runbun/templates/runbun/reviews.html
<!DOCTYPE html>

<html>
<head>
    {% load static %}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'runbun/css/style.css' %}">

    <title>runBun</title>
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
       <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="{% url 'runbun:index' %}">
			<img src="{% static 'runbun/img/runBun_logo.gif' %}" alt="Home" id="runbun-logo">
			run<strong>Bun</strong>
		   </a>
         </div>

         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

           <ul class="nav navbar-nav navbar-right text-center">
             <li><a href="{% url 'runbun:index' %}" class="nav-link">Home</a></li>
             <li><a href="{% url 'runbun:gallery' %}" class="nav-link">Gallery</a></li>
             <li><a href="{% url 'runbun:reviews' %}" class="nav-link current">Reviews</a></li>
             <li><a href="{% url 'runbun:contact' %}" class="nav-link">Contact Us</a></li>
             <li><a href="{% url 'runbun:about' %}" class="nav-link">About Us</a></li>
             <li><a href="{% url 'runbun:signin' %}" class="nav-link signin" id="signin-btn">Sign In</a></li>
             <li><a href="{% url 'runbun:cart' %}" class="nav-link shopping-cart" id="shopping-cart-btn"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a></li>
           </ul>


         </div><!-- /.navbar-collapse -->
       </div><!-- /.container-fluid -->
    </nav>


    <div class="container">
      <div class="jumbotron">
        <h1>This is the Reviews</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
      </div>
	</div> <!--container-->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="{% static 'runbun/js/main.js' %}"></script>

</body>
</html>